### ISSUE TITLE
UploadScanner bug

### ISSUE THREAD

**Issue by Bo0oM** [modzero/mod0BurpUploadScanner#18]
```
Traceback (most recent call last):
  File "/Users/bo0om/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 794, in processHttpMessage
    url = FloydsHelpers.u2s(iRequestInfo.getUrl().toString())
AttributeError: 'NoneType' object has no attribute 'toString'

```

🤔

**Comment by Bo0oM** [comment]
```
Traceback (most recent call last):
  File "/Users/bo0om/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 813, in processHttpMessage
    url = FloydsHelpers.u2s(iRequestInfo.getUrl().toString())
AttributeError: 'NoneType' object has no attribute 'toString'

Upload Scanner Version: 1.0.3

Jython version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
Java version: 1.8.0_112
```

**Comment by floyd-fuh** [comment]
See #17 . Thanks for reporting!
