### ISSUE TITLE
Unable to see Send To Upload Scanner

### ISSUE THREAD

**Issue by rudrasingh99** [modzero/mod0BurpUploadScanner#20]
Hey,

I've been using upload scanner for a while now but all of a sudden i'm unable to see the send to upload scanner but now.

SS attached 
![screen shot 2018-08-19 at 7 59 25 am](https://user-images.githubusercontent.com/25739971/44304858-1189f880-a386-11e8-8e7d-b68edef9a0cb.png)

**Comment by floyd-fuh** [comment]
Thanks for taking the time to report this issue.

That's super weird and I've never heard of such a problem. As the extension simply registers in the context menu on load and Burp automatically removes the context menu on unload, I don't think this is an extension issue.

First check that the extension is properly loaded in the "Extender - Extensions" tab, in the "Loaded" column the checkbox has to be checked.  

Could you also answer some questions:

1. Which Burp version are you using?
2. Which UploadScanner are you using?
3. How did you install UploadScanner (manually or via BApp)?

**Comment by rudysingh99** [comment]
Hey Thanks for super quick reply.

While my burp is updated (Burp 1.7.37) and i installed it via Bapp and i've enabled it still unable to see the options.

**Comment by floyd-fuh** [comment]
Can you check the extension tab an check if there are any exceptions in the "Errors" tab for the Upload Scanner? What's in the "Output" tab?

**Comment by floyd-fuh** [comment]
I really can't help if I don't get any infos. This could be anything. Closing for now.

**Comment by rudrasingh99** [comment]
Hey @floyd-fuh sorry for the late response. 
I've just noticed some strange error on the error console.


`Traceback (most recent call last):
  File "/Users/rudrapratapsingh/Downloads/upload-scanner-master/UploadScanner.py", line 497, in registerExtenderCallbacks
    self.deserialize_settings()
  File "/Users/rudrapratapsingh/Downloads/upload-scanner-master/UploadScanner.py", line 618, in deserialize_settings
    cm = pickle.loads(k.decode("base64"))
  File "/Users/rudrapratapsingh/jython2.7.0/Lib/encodings/base64_codec.py", line 42, in base64_decode
    output = base64.decodestring(input)
  File "/Users/rudrapratapsingh/jython2.7.0/Lib/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

	at org.python.core.PyException.doRaise(PyException.java:198)
	at org.python.core.Py.makeException(Py.java:1337)
	at org.python.core.Py.makeException(Py.java:1341)
	at org.python.core.Py.makeException(Py.java:1345)
	at org.python.core.Py.makeException(Py.java:1349)
	at org.python.pycode._pyx5.registerExtenderCallbacks$2(/Users/rudrapratapsingh/Downloads/upload-scanner-master/UploadScanner.py:514)
	at org.python.pycode._pyx5.call_function(/Users/rudrapratapsingh/Downloads/upload-scanner-master/UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$8.registerExtenderCallbacks(Unknown Source)
	at burp.cty.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
`

I'm not familiar with them.


Thanks

**Comment by floyd-fuh** [comment]
Now we are talking! Thanks for the exception trace. It seems something is going wrong when doing the deserialization. I'll surround that with a try catch in the next version so it will just start normally.

As a workaround for now, go to the "Target" tab and delete everything which is stored for "http://uploadscannerextension.local/". It might help or it might not... if it doesn't help, wait for the next version to be pushed to the BApp store.

**Comment by floyd-fuh** [comment]
Pull request lives here: https://github.com/PortSwigger/upload-scanner/pull/7

**Comment by floyd-fuh** [comment]
When you start Burp now, you should get an update of the Upload Scanner from BApp and then you should be able to use it again. Can you confirm?
