### ISSUE TITLE
UploadScanner bug

### ISSUE THREAD

**Issue by aSIHADHASJDADSGAJD** [modzero/mod0BurpUploadScanner#21]
```
Traceback (most recent call last):
  File "/root/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 903, in doActiveScan
    self.do_checks(injector)
  File "/root/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1029, in do_checks
    colab_tests.extend(self._xxe_xmp(injector, burp_colab))
  File "/root/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1029, in do_checks
    colab_tests.extend(self._xxe_xmp(injector, burp_colab))
  File "/root/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 2417, in _xxe_xmp
    return x.do_collaborator_tests(injector, burp_colab, injector.opts.get_enabled_file_formats())
  File "/root/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 5398, in do_collaborator_tests
    c = self._send_collab(injector, burp_colab, types, basename, content, old_xmp, new_xmp, issue)
  File "/root/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 5438, in _send_collab
    urr = self._make_http_request(injector, req, redownload_filename=filename)
  File "/root/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 4097, in _make_http_request
    attack = self._callbacks.makeHttpRequest(service, req)
byc: burp.byc

Upload Scanner Version: 1.0.4

Jython version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
Java version: 1.8.0_112
```

**Comment by floyd-fuh** [comment]
Wow, this is weird. I don't have a clue what `byc: burp.byc` would mean. 

I can tell you that the extension tried to do a XXE test with XMP metadata and in the end send an HTTP request over the Burp API makeHttpRequest. However, as long as I don't see the request I can't say what the problem actually was.

Also because `byc: burp.byc` is so cryptic I can't really know what is going on.

Can you answer the following questions?

1. Which Burp version are you using?
2. How did you install UploadScanner (manually or via BApp)?
3. Can you share the request that you were trying to scan (a redacted version should be fine too)?

**Comment by floyd-fuh** [comment]
Opened this with Portswigger: https://support.portswigger.net/customer/en/portal/questions/17382234-burp-byc?new=17382234
