### ISSUE TITLE
UploadScanner bug

### ISSUE THREAD

**Issue by yujitounai** [modzero/mod0BurpUploadScanner#23]
```
Traceback (most recent call last):
  File "C:\Users\yuji\AppData\Roaming\BurpSuite\bapps\b2244cbb6953442cb3c82fa0a0d908fa\UploadScanner.py", line 4818, in getInsertionPoints
    injector = MultipartInjector(base_request_response, self._global_opts, insertionPoint, self._helpers, BurpExtender.NEWLINE)
  File "C:\Users\yuji\AppData\Roaming\BurpSuite\bapps\b2244cbb6953442cb3c82fa0a0d908fa\UploadScanner.py", line 4580, in __init__
    self._default_file_extension = FloydsHelpers.u2s(os.path.splitext(self._insertionPoint.getBaseValue())[1]) or ''
  File "C:\Users\yuji\Downloads\jython-standalone-2.7.0.jar\Lib\ntpath.py", line 190, in splitext
    return genericpath._splitext(p, sep, altsep, extsep)
  File "C:\Users\yuji\Downloads\jython-standalone-2.7.0.jar\Lib\genericpath.py", line 91, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'

Upload Scanner Version: 1.0.5

Jython version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
Java version: 1.8.0_112
Burp version: Burp Suite Professional 2.0 06beta
Command line arguments: 
Was loaded from BApp: True
```

**Comment by floyd-fuh** [comment]
So this is just super random, getBaseValue() should return the base value, not None. But this is going to be mitigated in the next release.
