### ISSUE TITLE
UploadScanner bug

### ISSUE THREAD

**Issue by fenceposterror** [modzero/mod0BurpUploadScanner#24]
```
Traceback (most recent call last):
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 919, in doActiveScan
    self.do_checks(injector)
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1031, in do_checks
    colab_tests.extend(self._htaccess(injector, burp_colab))
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1031, in do_checks
    colab_tests.extend(self._htaccess(injector, burp_colab))
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1978, in _htaccess
    if urr.download_rr:
AttributeError: 'NoneType' object has no attribute 'download_rr'

Upload Scanner Version: 1.0.5

Jython version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
Java version: 1.8.0_112
Burp version: Burp Suite Professional 2.0 08beta
Command line arguments: 
Was loaded from BApp: True
```

The full one
```
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 6878, in get_matchers_for_url
    return self.with_global(hostport, self._collection[hostport])
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 6851, in with_global
    for alt_name in self._scope_mapping[name]:
KeyError: 'some.domain.tld'

	at org.python.core.PyException.doRaise(PyException.java:226)
	at org.python.core.Py.makeException(Py.java:1337)
	at org.python.pycode._pyx4.processHttpMessage$22(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py:880)
	at org.python.pycode._pyx4.call_function(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$8.processHttpMessage(Unknown Source)
	at burp.cdz.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Traceback (most recent call last):
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 838, in processHttpMessage
    matchers = self.dl_matchers.get_matchers_for_url(url)
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 6878, in get_matchers_for_url
    return self.with_global(hostport, self._collection[hostport])
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 6851, in with_global
    for alt_name in self._scope_mapping[name]:
KeyError: 'some.domain.tld'

	at org.python.core.PyException.doRaise(PyException.java:226)
	at org.python.core.Py.makeException(Py.java:1337)
	at org.python.pycode._pyx4.processHttpMessage$22(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py:880)
	at org.python.pycode._pyx4.call_function(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$8.processHttpMessage(Unknown Source)
	at burp.cdz.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Traceback (most recent call last):
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 838, in processHttpMessage
    matchers = self.dl_matchers.get_matchers_for_url(url)
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 6878, in get_matchers_for_url
    return self.with_global(hostport, self._collection[hostport])
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 6851, in with_global
    for alt_name in self._scope_mapping[name]:
KeyError: 'some.domain.tld'

	at org.python.core.PyException.doRaise(PyException.java:226)
	at org.python.core.Py.makeException(Py.java:1337)
	at org.python.pycode._pyx4.processHttpMessage$22(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py:880)
	at org.python.pycode._pyx4.call_function(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$8.processHttpMessage(Unknown Source)
	at burp.cdz.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Traceback (most recent call last):
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 838, in processHttpMessage
    matchers = self.dl_matchers.get_matchers_for_url(url)
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 6878, in get_matchers_for_url
    return self.with_global(hostport, self._collection[hostport])
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 6851, in with_global
    for alt_name in self._scope_mapping[name]:
KeyError: 'some.domain.tld'

	at org.python.core.PyException.doRaise(PyException.java:226)
	at org.python.core.Py.makeException(Py.java:1337)
	at org.python.pycode._pyx4.processHttpMessage$22(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py:880)
	at org.python.pycode._pyx4.call_function(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$8.processHttpMessage(Unknown Source)
	at burp.cdz.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Traceback (most recent call last):
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 919, in doActiveScan
    self.do_checks(injector)
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1031, in do_checks
    colab_tests.extend(self._htaccess(injector, burp_colab))
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1031, in do_checks
    colab_tests.extend(self._htaccess(injector, burp_colab))
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1978, in _htaccess
    if urr.download_rr:
AttributeError: 'NoneType' object has no attribute 'download_rr'

	at org.python.core.PyException.doRaise(PyException.java:226)
	at org.python.core.Py.makeException(Py.java:1337)
	at org.python.pycode._pyx4.doActiveScan$27(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py:926)
	at org.python.pycode._pyx4.call_function(/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$8.doActiveScan(Unknown Source)
	at burp.cld.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Traceback (most recent call last):
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 7482, in run
    self.func()
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 8911, in _start_scan_thread
    self._burp_extender.doActiveScan(self.scan_controler.brr, insertionPoint, options=self)
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 919, in doActiveScan
    self.do_checks(injector)
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1031, in do_checks
    colab_tests.extend(self._htaccess(injector, burp_colab))
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1031, in do_checks
    colab_tests.extend(self._htaccess(injector, burp_colab))
  File "/home/fpe/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1978, in _htaccess
    if urr.download_rr:
AttributeError: 'NoneType' object has no attribute 'download_rr'
```

**Comment by floyd-fuh** [comment]
This was already fixed in commit 80eb37688aff75d0e9297c8cfda003b1782a689b but hasn't populated to BApp store yet. Use this github version if fix is necessary.
