### ISSUE TITLE
UploadScanner bug

### ISSUE THREAD

**Issue by jplopezy** [modzero/mod0BurpUploadScanner#3]
```
Traceback (most recent call last):
  File "C:\Users\test\AppData\Roaming\BurpSuite\bapps\b2244cbb6953442cb3c82fa0a0d908fa\UploadScanner.py", line 798, in processHttpMessage
    matchers = self.dl_matchers.get_matchers_for_url(url)
  File "C:\Users\test\AppData\Roaming\BurpSuite\bapps\b2244cbb6953442cb3c82fa0a0d908fa\UploadScanner.py", line 6581, in get_matchers_for_url
    hostport = self._get_host(url)
  File "C:\Users\test\AppData\Roaming\BurpSuite\bapps\b2244cbb6953442cb3c82fa0a0d908fa\UploadScanner.py", line 6608, in _get_host
    x = urlparse.urlparse(url)
  File "C:\Users\test\Downloads\jython-standalone-2.7.0.jar\Lib\urlparse.py", line 140, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "C:\Users\test\Downloads\jython-standalone-2.7.0.jar\Lib\urlparse.py", line 202, in urlsplit
    rest = url[i+1:]
OutOfMemoryError: java.lang.OutOfMemoryError: GC overhead limit exceeded

```

**Comment by floyd-fuh** [comment]
This is very weird that this happens at this place, as out of memory could happen everywhere and is not really something this extension could prevent. What was your memory limit for Burp?
