### ISSUE TITLE
UploadScanner bug when loosing connection

### ISSUE THREAD

**Issue by vollkorn1982** [modzero/mod0BurpUploadScanner#35]
```
Traceback (most recent call last):
  File "/home/work/Dokumente/Tools/UploadScanner/UploadScanner.py", line 875, in doActiveScan
    self.do_checks(injector)
  File "/home/work/Dokumente/Tools/UploadScanner/UploadScanner.py", line 960, in do_checks
    self._jsp_rce(injector)
  File "/home/work/Dokumente/Tools/UploadScanner/UploadScanner.py", line 960, in do_checks
    self._jsp_rce(injector)
  File "/home/work/Dokumente/Tools/UploadScanner/UploadScanner.py", line 1594, in _jsp_rce
    self._servercode_rce_backdoored_file(injector, self._jsp_gen_payload_expression_lang, self._jsp_rce_params,
  File "/home/work/Dokumente/Tools/UploadScanner/UploadScanner.py", line 1696, in _servercode_rce_backdoored_file
    self._send_simple(injector, types, basename, content, redownload=True)
  File "/home/work/Dokumente/Tools/UploadScanner/UploadScanner.py", line 3843, in _send_simple
    urrs.append(self._make_http_request(injector, req, redownload_filename=x))
  File "/home/work/Dokumente/Tools/UploadScanner/UploadScanner.py", line 3991, in _make_http_request
    attack = self._callbacks.makeHttpRequest(service, req)
RuntimeException: java.lang.RuntimeException: <URL redacted>

```

**Comment by vollkorn1982** [comment]
I used an outdated version and installed the recent version of the plugin, but I could not reproduce this bug in *neither* version. Closing for now.
