### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by proabiral** [modzero/mod0BurpUploadScanner#36]
```
Traceback (most recent call last):
  File "/home/bb/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1026, in run_flexiinjector
    self.do_checks(fi)
  File "/home/bb/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1143, in do_checks
    colab_tests.extend(self._ssrf(injector, burp_colab))
  File "/home/bb/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1143, in do_checks
    colab_tests.extend(self._ssrf(injector, burp_colab))
  File "/home/bb/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 2996, in _ssrf
    self._send_simple(injector, self.URL_TYPES, basename + "Mal", content, redownload=True)
  File "/home/bb/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 4225, in _send_simple
    urrs.append(self._make_http_request(injector, req, redownload_filename=x))
  File "/home/bb/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 4380, in _make_http_request
    attack = self._callbacks.makeHttpRequest(service, req)
RuntimeException: java.lang.RuntimeException

Upload Scanner Version: 1.0.8

Extension code location: run_flexiinjector
Jython version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[OpenJDK 64-Bit Server VM (Oracle Corporation)]
Java version: 1.8.0_191
Burp version: Burp Suite Professional 1.7 32
Command line arguments: 
Was loaded from BApp: True
Request: 'POST /v1_1/dedpsogvz/upload HTTP/1.1\r\nHost: api.cloudinary.com\r\nConnection: close\r\nContent-
Length: 23281\r\nAccept: application/json, text/javascript, */*; q=0.01\r\nX-Requested-With: XMLHttpRequest\r\nX-Unique-Upload-Id:
16e7c4038.de12a\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/70.0.3538.77 Safari/537.36\r\nContent-Type: multipart/form-data;
boundary=----WebKitFormBoundaryaUA27ND0r4frjqCN\r\nAccept-Encoding: gzip,
deflate\r\nAccept-Language: en-US,en;q=0.9,ne;q=0.8\r\n\r\n------
WebKitFormBoundaryaUA27ND0r4frjqCN\r\nContent-Disposition: form-data;
name="use_filename"\r\n\r\ntrue\r\n------WebKitFormBoundaryaUA27ND0r4frjqCN\r\nContent-Disposition:
form-data; name="unique_filename"\r\n\r\nfalse\r\n------WebKitFormBoundaryaUA27ND0r4frjqCN\r
\nContent-Disposition: form...
```

**Comment by pajswigger** [comment]
Can you share your Burp debug ID? It's in User options > Misc > Performance Feedback

makeHttpRequest should not be throwing an exception, and this will help us identify why it is
