### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 1135** [modzero/mod0BurpUploadScanner#39]
```
Traceback (most recent call last):
  File "/Users/lin/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 981, in doActiveScan
    self.do_checks(injector)
  File "/Users/lin/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1078, in do_checks
    colab_tests.extend(self._ghostscript(injector, burp_colab))
  File "/Users/lin/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1078, in do_checks
    colab_tests.extend(self._ghostscript(injector, burp_colab))
  File "/Users/lin/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1587, in _ghostscript
    self._send_sleep_based(injector, basename + cmd_name, sleep_content, self.GS_TYPES, injector.opts.sleep_time, issue)
  File "/Users/lin/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 4322, in _send_sleep_based
    resp = self._make_http_request(injector, req, throttle=False)
  File "/Users/lin/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 4380, in _make_http_request
    attack = self._callbacks.makeHttpRequest(service, req)
ffn: burp.ffn

Upload Scanner Version: 1.0.8

Extension code location: doActiveScan
Jython version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
Java version: 1.8.0_121
Burp version: Burp Suite Professional 2.0 beta
Command line arguments: 
Was loaded from BApp: True
Request: 'POST /sandbox/fileupload?env=10r9&time=2&analyzer=1 HTTP/1.1\r\nHost: sandbox.ti.360.net\r\nUser-
Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0\r\nAccept:
*/*\r\nAccept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2\r\nAccept-
Encoding: gzip, deflate\r\nReferer: https://sandbox.ti.360.net/sandbox/page\r\nContent-Type:
multipart/form-data; boundary=---------------------------9373175712441266482135785744\r\nContent-
Length: 737\r\nConnection: close\r\nCookie: session=5cfb1597-26cb-4a43-bf1d-048889c7608d\r\n\r\n
-----------------------------9373175712441266482135785744\r\nContent-Disposition: form-data;
name="file"; filename="333"\r\nContent-Type: application/octet-stream\r\n\r\nGET /sandbox/page/detai
l?type=file&sha1=4e449d8bd80631c3e294e0d1a1845db7a7cb06b8&id=AWhUhRPbNoqRgONUvpW9&env=&time=
HTTP/1.1\r\nHost: sandbox.ti.360.net\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14;
rv:64.0) Gecko/20100101 Firefox/...
```

**Comment by floyd-fuh** [comment]
As the Burp API apparently does not report a proper minor version (2.0.17 or such) they can not deobfuscate that burp.ffn properly and neither can I. Closing for now
