### ISSUE TITLE
Java Exception

### ISSUE THREAD

**Issue by Hipapheralkus** [modzero/mod0BurpUploadScanner#4]
I'm running Burp 1.7.34 and it has completely frozen. I checked the jstack, and I can see the trance for an exception coming from your extender:
```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.112-b15 mixed mode):


"pool-7-thread-3596616" #3596830 prio=5 os_prio=0 tid=0x0000000041d14000 nid=0x78dc waiting for monitor entry [0x000000005047e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at burp.o7h.a(Unknown Source)
	at burp.o7h.a(Unknown Source)
	at burp.alg.b(Unknown Source)
	at burp.cdg.a(Unknown Source)
	at burp.hpf.a(Unknown Source)
	at burp.hpf.next(Unknown Source)
	at burp.n1g.a(Unknown Source)
	at burp.n1g.b(Unknown Source)
	- locked <0x00000007465fe988> (a java.lang.Object)
	at burp.bgc.a(Unknown Source)
	at burp.a4c.analyzeRequest(Unknown Source)
	at burp.a4c.analyzeRequest(Unknown Source)
	at burp.jqh.analyzeRequest(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx4.processHttpMessage$22(E:\BurpSuite Settings and Extensions\Extenders\Upload_Scanner\UploadScanner.py:838)
	at org.python.pycode._pyx4.call_function(E:\BurpSuite Settings and Extensions\Extenders\Upload_Scanner\UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$8.processHttpMessage(Unknown Source)
	at burp.drd.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```
I'm not entirely certain if the problem is on your side, but I can't access the Alerts view of Burp, nor Error view in extenders because it froze, so I can't check if something appears in those logs.

**Comment by floyd-fuh** [comment]
I had a quick look and all we do there is getting a request from Burp in processHttpMessage and then pass it to Burp‘s helper function analyzeRequest, where it gets stuck. So i think this is rather a coincidence that it is this plugin that gets stuck, that‘s a normal thing to do.

If you could answer a couple of questions this would be helpful:

Is there anything special about the requests going through Burp?

Are the requests from a regular browser?

Is this reproducible on your side?

Can you disclose the website tested?

Better post this on the Burp support forums and reference this issue.

**Comment by Hipapheralkus** [comment]
I've exchanged a few messages with Portswigger support and they also confirmed that this issue is not local to the Upload Scanner. Sorry for making fuzz about it:)

**Comment by floyd-fuh** [comment]
No worries, thanks for taking the time to report the bug nevertheless :)
