### ISSUE TITLE
OSError: [Errno 1] Operation not permitted:

### ISSUE THREAD

**Issue by arbazkiraak** [modzero/mod0BurpUploadScanner#40]
Here's the stderr tab while loading the `UploadScanner.py`

```
Traceback (most recent call last):
  File "C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py", line 514, in registerExtenderCallbacks
    self._create_ui()
  File "C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py", line 559, in _create_ui
    self._global_opts = OptionsPanel(self, self._callbacks, self._helpers, global_options=True)
  File "C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py", line 8451, in __init__
    os.chmod(path, st.st_mode | stat.S_IEXEC)
OSError: [Errno 1] Operation not permitted: 'C:\\Program Files\\BurpSuitePro\\Burp New Out of Plugins\\mod0BurpUploadScanner-master\\bin\\exiftool.pl'

	at org.python.core.Py.OSError(Py.java:162)
	at org.python.modules.posix.PosixModule.chmod(PosixModule.java:314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:478)
	at org.python.core.PyObject.__call__(PyObject.java:482)
	at org.python.pycode._pyx5.__init__$437(C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py:8488)
	at org.python.pycode._pyx5.call_function(C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:19)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:1713)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:394)
	at org.python.pycode._pyx5._create_ui$3(C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py:573)
	at org.python.pycode._pyx5.call_function(C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx5.registerExtenderCallbacks$2(C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py:536)
	at org.python.pycode._pyx5.call_function(C:\Program Files\BurpSuitePro\Burp New Out of Plugins\mod0BurpUploadScanner-master\UploadScanner.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:198)
	at org.python.core.PyFunction.__call__(PyFunction.java:482)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:218)
	at org.python.core.PyMethod.__call__(PyMethod.java:213)
	at org.python.core.PyObject._jcallexc(PyObject.java:3626)
	at org.python.core.PyObject._jcall(PyObject.java:3658)
	at org.python.proxies.__main__$BurpExtender$8.registerExtenderCallbacks(Unknown Source)
	at burp.b0h.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

```

OS: Windows 10 x64
Burp Version : v1.7.37

* While installing it from BApp store works fine.

**Comment by arbazkiraak** [comment]
* Issue has been solved, it was due to permissions.

**Comment by floyd-fuh** [comment]
I'm glad you were able to figure this out. It indeed seems to be a permission issue. In general I recommend to install the extension from BApp, as this will keep you up to date with the latest fixes and features. Moreover, installation issues such as this should not occur. Happy hacking!
