### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DebyN** [modzero/mod0BurpUploadScanner#41]
```
Traceback (most recent call last):
  File "/home/debby/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 981, in doActiveScan
    self.do_checks(injector)
  File "/home/debby/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1073, in do_checks
    colab_tests.extend(self._magick(injector, burp_colab))
  File "/home/debby/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1073, in do_checks
    colab_tests.extend(self._magick(injector, burp_colab))
  File "/home/debby/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 1439, in _magick
    self._send_sleep_based(injector, basename, content, types, injector.opts.sleep_time, issue)
  File "/home/debby/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 4322, in _send_sleep_based
    resp = self._make_http_request(injector, req, throttle=False)
  File "/home/debby/.BurpSuite/bapps/b2244cbb6953442cb3c82fa0a0d908fa/UploadScanner.py", line 4380, in _make_http_request
    attack = self._callbacks.makeHttpRequest(service, req)
ffn: burp.ffn

Upload Scanner Version: 1.0.8

Extension code location: doActiveScan
Jython version: 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11) 
[OpenJDK 64-Bit Server VM (Oracle Corporation)]
Java version: 1.8.0_181
Burp version: Burp Suite Professional 2.0 beta
Command line arguments: 
Was loaded from BApp: True
Request: 'POST /users/photo_upload HTTP/1.1\r\nHost: cougarlife.com\r\nUser-Agent: Mozilla/5.0 (X11; Ubuntu;
Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0\r\nAccept: */*\r\nAccept-Language: en-
US,en;q=0.5\r\nAccept-Encoding: gzip, deflate\r\nReferer: https://cougarlife.com/search/public\r
\nContent-Type: multipart/form-data;
boundary=---------------------------19294246521380533560987720335\r\nContent-Length:
300759\r\nCookie: __cfduid=dc89051f60508e2163028a0ce7fe0dbe21550484404;
r2=eJyrrgUAAXUA%2BQ%3D%3D%0A; locale=en_US; ajaxim_token=; _em_session_id=BAh7C0kiC2xvY2FsZQY6BkVGSS
IKZW5fVVMGOwBUSSIMY291bnRyeQY7AEZJ%250AIgdJRAY7AEZJIgxsYW5kaW5nBjsARkkiFWluZGV4X2FuZGVyc29uX2IGOwBU%
250ASSIQX2NzcmZfdG9rZW4GOwBGSSIxZXN1NlZyazhwTGhzVFNEdnBqU09yUGZ2%250AYk1WY1FpNE9UN3lKclAyNkVVQT0GOwB
GSSIUdHJhY2tpbmdfcGl4ZWxzBjsA%250ARjBJIgxyZWZlcmVyBjsARiIcaHR0cHM6Ly9jb3VnYXJsaWZlLmNvbS8%253D--
3d0023126c41dd53474be584be00cfb926bbd0f1; c___vid=43cbf0ade8d045098241adb38cf401e4;
timezone=420\r\nDNT: 1\r\nConnectio...
```

**Comment by floyd-fuh** [comment]
As the Burp API apparently does not report a proper minor version (2.0.17 or such) they can not deobfuscate that burp.ffn properly and neither can I. Closing for now
