### ISSUE TITLE
UploadScanner bug

### ISSUE THREAD

**Issue by b4sm** [modzero/mod0BurpUploadScanner#6]
```
Traceback (most recent call last):
  File "C:\Users\b4sm\Desktop\mod0BurpUploadScanner-master\UploadScanner.py", line 914, in run_flexiinjector
    self.do_checks(fi)
  File "C:\Users\b4sm\Desktop\mod0BurpUploadScanner-master\UploadScanner.py", line 928, in do_checks
    burp_colab = BurpCollaborator(self._callbacks)
  File "C:\Users\b4sm\Desktop\mod0BurpUploadScanner-master\UploadScanner.py", line 4142, in __init__
    self.is_ip_collaborator = '/' in FloydsHelpers.u2s(callbacks.createBurpCollaboratorClientContext().generatePayload(True))
AttributeError: 'NoneType' object has no attribute 'generatePayload'

```

**Comment by floyd-fuh** [comment]
Should be fixed with https://github.com/PortSwigger/upload-scanner/pull/3
